# docker-enginge: 17.06.0+
# docker-compose.yml preferes spaces over tabs
version: '3.3'
services:
   nginx:
     depends_on:
         - livereload
     container_name: alpine.nginx
     build:
         labels:
             alpine.nginx.description: "template for boilerplate"
         context: ./
         dockerfile: ./dockerfiles/alpine.nginx.dockerfile.sh
     volumes:
         - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./app/nginx/conf.d/:/etc/nginx/conf.d/
         - ./app/hugo/blog/public:/usr/share/nginx/html:rw
     restart: always
     command: ["nginx"]
     image: researchranks/alpine.nginx:latest
     expose:
         - 80
         - 443
     ports:
         - 80:80
         - 443:443
   hugo:
      container_name: alpine.hugo
      build:
         labels:
            alpine.hugo.description: "template for boilerplate"
         context: ./
         dockerfile: ./dockerfiles/alpine.hugo.dockerfile.sh
      volumes:
         - ./dockerfiles/alpine.waitforit.sh:/waitforit.sh
         - ./app/hugo/blog:/var/www/app/:rw
      restart: always
      expose:
         - 80
         - 1313
      hostname: hugo
      extra_hosts:
       - "localhost:127.0.0.1"
      ports:
          - 1313:1313
      #note: production mode inlucde
      #  --appendPort=false \
      #  --buildDrafts \
      #  --cleanDestinationDir \
      #  --renderToDisk \
      entrypoint: "hugo server \
       --baseURL='localhost' \
       --bind='0.0.0.0' \
       --buildDrafts \
       --cleanDestinationDir \
       --disableFastRender \
       --ignoreCache \
       --liveReloadPort=1313 \
       --navigateToChanged \
       --noHTTPCache \
       --port=1313 \
       --renderToDisk \
       --verbose \
       --watch"     
      image: researchranks/alpine.hugo:latest

   livereload:
      container_name: alpine.livereload
      depends_on:
          - hugo
      build:
         labels:
            alpine.livereload.description: "template for boilerplate"
         context: ./
         dockerfile: ./dockerfiles/alpine.livereload.dockerfile.sh
      entrypoint: node bin/livereload.js /usr/src/livereload-watch -u true -d --exts 'html'
      expose:
         - 35729
      ports:
         - 35729:35729
      volumes:
         - ./app/hugo/blog/:/usr/src/livereload-watch
      image: researchranks/alpine.livereload:latest